---
title: "example"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr)
library(splines)
library(doParallel)
library(foreach)
library(tidyr)
library(MASS)
library(nnet)
library(car)
delta <- 0.2
m <- 1000
n <- 100
B <- 50
dof = 5

l = 0.4
p = 0.2
r <- runif(m)
    alpha <- if_else(r < (1- p), 0, 
                     if_else(r < (1- p/2), runif(m, -l-delta, -l), runif(m, l,l+delta))
    )
    r <- runif(m)
    beta <- if_else(r < (1- p), 0, 
                    if_else(r < (1- p/2), runif(m, -l-delta, -l), runif(m, l,l+delta))
    )
    tp <- abs(alpha) > 0  
    tn <- alpha == 0 
    
    ## Generate X,Z
    
    
    Z <- matrix(rnorm(n*3), nrow = n)
    rho = 1
    softMax <- function(x){
    expx <- exp(rho* x)
    return(expx/sum(expx))
    }
    u = colMeans(Z)
    prob = softMax(u)
    X = sample(1:3, size = n, replace = T, prob = prob)
    X = as.factor(X)
    ##Generate Y
    
    Y = matrix(nrow = m, ncol = n)
    for(j in 1:m)  
    {
      Y[j,] <- rpois(n, lambda = exp(alpha[j]*as.numeric(X) + beta[j]*(Z%*%c(1,0.5,0.2))))
      
    }

    j = 3
    Y = Y[j,]
fit2 = glm(Y ~ X, family = poisson(link = log), control = glm.control(maxit = 100))
fit1 = glm(Y ~ X + Z, family = poisson(link = log), control = glm.control(maxit = 100))
t2 = anova(fit2)$F[1]
t1 = anova(fit1)$F[1]
fit1
anova(fit1)
anova(fit2)
t1
t2

```
Best I can do is use the Deviance.
